### ISSUE TITLE
Update KDE runtime to 6.X

### ISSUE THREAD

**Issue by notfirefox** [flathub/org.kde.kile#241]
Update the KDE runtime to a newer version, preferably to the latest version which as of now is 6.6.
For comparison, see this pull request for Okular: https://github.com/flathub/org.kde.okular/pull/341

**Comment by travier** [comment]
The KF6 port has just been merged and will be in the next release: https://invent.kde.org/office/kile/-/merge_requests/74

**Comment by travier** [comment]
3.0b4 has been released and we are already shipping pre-releases so we can use that.

**Comment by travier** [comment]
Please test the build from https://github.com/flathub/org.kde.kile/pull/242 and report any positive or negative results.

**Comment by travier** [comment]
Thanks for the feedback!
